export type ProductSectionName = 'Analyze' | 'Review' | 'Player Value' | 'Training' | 'System / Lab'

export interface ProductNavigationItem {
  label: string
  path: string
  description: string
  routeName: string
  status?: 'command-center' | 'core' | 'supporting' | 'detail'
}

export interface ProductNavigationSection {
  name: ProductSectionName
  description: string
  items: ProductNavigationItem[]
}

export const productNavigationSections: ProductNavigationSection[] = [
  {
    name: 'Analyze',
    description: 'Turn video projects into calibrated tracking, decisions, and coach-facing reporting artifacts.',
    items: [
      {
        label: 'Project Workspace',
        path: '/projects/:projectId',
        routeName: 'project',
        description: 'Project metadata, upload state, extracted frames, and MVP pipeline entry points.',
        status: 'core'
      },
      {
        label: 'Calibration',
        path: '/projects/:projectId/calibration',
        routeName: 'calibration',
        description: 'Manual court keypoint marking and homography save flow for an extracted frame.',
        status: 'core'
      },
      {
        label: 'Pipeline',
        path: '/projects/:projectId/pipeline',
        routeName: 'pipeline',
        description: 'Guided project pipeline from calibration into tracking and review.',
        status: 'core'
      },
      {
        label: 'Tracking',
        path: '/projects/:projectId/tracking',
        routeName: 'tracking',
        description: 'Run deterministic MVP tracking and inspect frame overlays plus 2D court projection.',
        status: 'core'
      },
      {
        label: 'Coach Reports',
        path: '/reports/coach',
        routeName: 'coach-reports',
        description: 'Existing generated coach report summaries and evidence, without creating new analytics features.',
        status: 'supporting'
      }
    ]
  },
  {
    name: 'Review',
    description: 'Queue, inspect, and resolve human review work generated by tracking and source artifacts.',
    items: [
      {
        label: 'Review Queue',
        path: '/review-queue',
        routeName: 'review-queue',
        description: 'Operational review items, priorities, and action workflow entry points.',
        status: 'core'
      },
      {
        label: 'Tracking Review',
        path: '/projects/:projectId/tracking-review',
        routeName: 'tracking-review',
        description: 'Save manual tracking patches and cleaned tracking artifacts for a project.',
        status: 'core'
      },
      {
        label: 'Reference Videos',
        path: '/reference-videos',
        routeName: 'reference-videos',
        description: 'Manage reference clips that support review, rules, and quiz authoring workflows.',
        status: 'supporting'
      },
      {
        label: 'Reference Video Detail',
        path: '/reference-videos/:referenceId',
        routeName: 'reference-video-detail',
        description: 'Inspect a single reference video and its linked notes or drafts.',
        status: 'detail'
      }
    ]
  },
  {
    name: 'Player Value',
    description: 'Build, explain, and inspect local Player Value summaries and trends.',
    items: [
      {
        label: 'Player Value Summary',
        path: '/player-value',
        routeName: 'player-value',
        description: 'Explainable alias-based Player Value table built from local artifacts.',
        status: 'core'
      },
      {
        label: 'Player Value Trends',
        path: '/player-value/trends',
        routeName: 'player-value-trends',
        description: 'Trend view for existing Player Value time-series artifacts.',
        status: 'supporting'
      },
      {
        label: 'Player Value Evidence',
        path: '/player-value/:projectId/:playerKey',
        routeName: 'player-value-detail',
        description: 'Detailed evidence, component breakdown, and warnings for one player summary.',
        status: 'detail'
      }
    ]
  },
  {
    name: 'Training',
    description: 'Role-based learning, decision quizzes, drills, and practice planning flows.',
    items: [
      {
        label: 'Choose Training Role',
        path: '/start',
        routeName: 'role-entry',
        description: 'Select a role profile before entering role-aware training flows.',
        status: 'core'
      },
      {
        label: 'Player Home',
        path: '/player-home',
        routeName: 'player-home',
        description: "Simple player-facing view of today's focus, drill, and next action.",
        status: 'core'
      },
      {
        label: 'Training Lobby',
        path: '/training',
        routeName: 'training-lobby',
        description: 'Role-aware training hub for recommended situations and next steps.',
        status: 'core'
      },
      {
        label: 'Situations',
        path: '/situations',
        routeName: 'situation-preview',
        description: 'Preview decision situations used by role and training experiences.',
        status: 'supporting'
      },
      {
        label: 'Quiz Builder',
        path: '/projects/:projectId/quiz-builder',
        routeName: 'quiz-builder',
        description: 'Create decision quiz prompts from existing project/reference artifacts.',
        status: 'supporting'
      },
      {
        label: 'Quiz Play',
        path: '/projects/:projectId/quiz/:promptId',
        routeName: 'quiz-play',
        description: 'Play a saved decision quiz prompt.',
        status: 'detail'
      },
      {
        label: 'Drills',
        path: '/drills',
        routeName: 'drills',
        description: 'Browse the drill catalog used by recommendations and plans.',
        status: 'supporting'
      },
      {
        label: 'Practice Plans',
        path: '/practice-plans',
        routeName: 'practice-plans',
        description: 'Build and inspect practice plans from existing drill and player artifacts.',
        status: 'supporting'
      },
      {
        label: 'Practice Executions',
        path: '/practice-executions',
        routeName: 'practice-executions',
        description: 'List practice execution feedback signals and completion state.',
        status: 'supporting'
      },
      {
        label: 'Practice Execution Detail',
        path: '/practice-executions/:executionId',
        routeName: 'practice-execution-detail',
        description: 'Inspect a single practice execution and its feedback signal details.',
        status: 'detail'
      }
    ]
  },
  {
    name: 'System / Lab',
    description: 'Command center, orchestration, source setup, rules, model registry, and local lab operations.',
    items: [
      {
        label: 'Development Dashboard',
        path: '/development-dashboard',
        routeName: 'development-dashboard',
        description: 'Main dashboard for progress, health summaries, recommended next steps, and grouped navigation.',
        status: 'command-center'
      },
      {
        label: 'Home / Intake',
        path: '/',
        routeName: 'home',
        description: 'Create projects, load sample data, and access legacy intake quick links.',
        status: 'core'
      },
      {
        label: 'Workflows',
        path: '/workflows',
        routeName: 'workflows',
        description: 'Guided operational workflows created from dashboard or review actions.',
        status: 'supporting'
      },
      {
        label: 'Workflow Detail',
        path: '/workflows/:workflowId',
        routeName: 'workflow-detail',
        description: 'Step through one guided workflow and its linked artifact.',
        status: 'detail'
      },
      {
        label: 'Local Lab',
        path: '/local-lab',
        routeName: 'local-lab',
        description: 'Local source governance and lab-only operational utilities.',
        status: 'supporting'
      },
      {
        label: 'Model Registry',
        path: '/model-registry',
        routeName: 'model-registry',
        description: 'Inspect recognition model registry state and active model metadata.',
        status: 'supporting'
      },
      {
        label: 'Decision Rules',
        path: '/decision-rules',
        routeName: 'decision-rules',
        description: 'Manage existing decision rule sets and reference-derived rule drafts.',
        status: 'supporting'
      }
    ]
  }
]

export const primaryNavigationItems = productNavigationSections.flatMap((section) =>
  section.items
    .filter((item) => item.status !== 'detail' && !item.path.includes(':'))
    .map((item) => ({ ...item, section: section.name }))
)
